### PR TITLE
added the ability to filter, and added supporting tests

### PR DESCRIPTION
**Pull request by zachdaniel**

### CODE REVIEW

**Comment by zachdaniel** [comment]
The interface for this looks like this.
```
string() |> except(:blank) |> as_stream() |> Enum.take(5)
```
In the case that a filter with that name doesn't exist, we throw an argument error.

You can also pass functions in 

```
def blank, do: #...
string() |> except(&blank/1) |> as_stream() |> Enum.take(5)
```

You can also name them yourself, in the case that you ever want to introspect the generator/state
```
string() |> except({:blank, &blank/1}) |> as_stream() |> Enum.take(5)
```

**Comment by pragdave** [comment]
What do you think about moving `except` to VG?

**Comment by zachdaniel** [comment]
Yeah, looking at it now thats definitely the best place for it :)

**Comment by zachdaniel** [comment]
I'll write up some docs for it there, and provide some examples as well.  I also added a fallthrough case for exact match, so that if you say `integer() |> except(5)` it will do what you expect.

**Comment by zachdaniel** [comment]
I'll have something later on tonight, thanks for the quick response time and assistance!

**Comment by zachdaniel** [comment]
@pragdave What do you think?

**Comment by zachdaniel** [comment]
@pragdave Just pinging to see if you've had any thoughts on this :D

**Comment by zachdaniel** [comment]
@pragdave ping!  Just curious if you've had a chance to peek at this, or might have one in the future.

**Comment by zachdaniel** [comment]
@pragdave Would love to get this either in or something similar so we can get off of our own fork :D

**Comment by Dzol** [comment]
Hey @pragdave,

This is something we'd really like to see too!

**Comment by pragdave** [comment]
Many thanks for this.

And you used `with`, for which you get bonus points and a "huzzah!"


Dave

**Pull request merged**
