### PR TITLE
Added a `can_be_blank?` configuration for strings

### PR DESCRIPTION
**Pull request by zachdaniel**
I imagine that there is more to consider here, like the possibility of an infinite loop.  Thoughts?

### CODE REVIEW

**Comment by pragdave** [comment]
Could this be implemented by setting the minimum length to 1?

**Comment by zachdaniel** [comment]
Unfortunately, no.  The real statement is that the string itself can't consist only of whitespace.  Setting the minimum length to 1 wouldn't preclude the strings `" "` and `"     "` and so on.  I have no problems if there is a better way to implement that requirement though.  One of the things we're also trying to do is use the introspection offered by the `State` struct to generate documentation as well.  We can wrap these generators with our own structs, and add context that way (so if a specific attribute is true, we filter the stream, or something to that effect) but I think it might be nice to instead make the underlying generators more introspectable, with named filters and the like.

**Comment by pragdave** [comment]
What if I implemented something like this

~~~
except(string(min: 1, max: 20), ~r/^\s+$/))
~~~

~~~
string(min: 1, max: 20) |> except(~r/^\s+$/)
~~~

That seems more general purpose.

**Comment by zachdaniel** [comment]
@pragdave I like it.  I think it might be nice to also implement named filters, to really aid in readability/inspection.  So, as an example, ours could read like `string(min: 1, max: 255) |> except(:blank_string)`.  Then, instead of backing them with regexes, we just back them with one arg functions that can be passed to `Stream.reject/1`

**Comment by zachdaniel** [comment]
closing in favor of #5

**Pull request closed without merging**
